name: sleapyfaces
channels:
  - conda-forge
dependencies:
  - babel
  - click
  - ffmpeg-python
  - future
  - h5py
  - hdf5
  - ipykernel
  - ipython
  - ipython_genutils
  - ipywidgets
  - joblib
  - jupyter
  - jupyter_client
  - jupyter_console
  - jupyter_core
  - jupyter_events
  - jupyter_server
  - jupyter_server_terminals
  - jupyterlab
  - jupyterlab_pygments
  - jupyterlab_server
  - jupyterlab_widgets
  - matplotlib-inline
  - nbclassic
  - nbclient
  - nbconvert
  - nbconvert-core
  - nbformat
  - notebook
  - packaging
  - pandas
  - pickleshare
  - pip
  - plotly
  - pyopenssl
  - python-dateutil
  - python-fastjsonschema
  - requests
  - scikit-learn
  - scipy
  - setuptools
  - six
  - wheel
  - yaml
  - pip:
      - contourpy
      - cython
      - matplotlib
      - more-itertools
      - numexpr
      - pathvalidate
      - pillow
      - pyparsing
      - pytest
      - pytest-cov
      - python-configuration
      - python-rapidjson
      - seaborn
      - sleapyfaces
      - statsmodels
      - tables


