site_name: SLEAPyFaces Documentation
nav:
  - Home: index.md
  - Getting Started: gettingstarted.md
  - Project Structure: projectstructure.md
  - API Reference: api.md
  - Change Log: changelog.md
theme: readthedocs
